name: Test serets

on:
  push:
    branches: [ci/circleci-setup]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar secrets
        run: |
          if [ ${#UNITY_LICENSE} -gt 1000 ]; then
            echo "UNITY_LICENSE  → OK (longitud: ${#UNITY_LICENSE}"
          else
            echo "UNITY_LICENSE  → ERROR (vacío o muy corto)"
          fi

          if [ ${#UNITY_EMAIL} -gt 5 ]; then
            echo "UNITY_EMAIL     → OK longitud: ${#UNITY_EMAIL}"
          else
            echo "UNITY_EMAIL     → ERROR (vacío)"
          fi

          if [ ${#UNITY_PASSWORD} -gt 5 ]; then
            echo "UNITY_PASSWORD  → OK longitud: ${#UNITY_PASSWORD}"
          else
            echo "UNITY_PASSWORD  → ERROR (vacío)"
          fi
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
